# pylint: disable=missing-module-docstring
from django.urls import path
from . import views

urlpatterns = [
    # CADASTROS DE CLIENTES
    path(
        "",
        views.ClienteListView.as_view(),
        name="cliente_list",
    ),
    path(
        "new/",
        views.ClienteCreateView.as_view(),
        name="cliente_new",
    ),
    path(
        "<int:pk>/detail/",
        views.ClienteDetailView.as_view(),
        name="cliente_detail",
    ),
    path(
        "<int:pk>/edit/",
        views.ClienteUpdateView.as_view(),
        name="cliente_edit",
    ),
    path(
        "<int:pk>/delete/",
        views.ClienteDeleteView.as_view(),
        name="cliente_delete",
    ),
    # PERFIS DE CLIENTES
    path(
        "perfil/",
        views.PerfilClienteListView.as_view(),
        name="perfil_cliente_list",
    ),
    path(
        "perfil/new/",
        views.PerfilClienteCreateView.as_view(),
        name="perfil_cliente_new",
    ),
    path(
        "perfil/<int:pk>/detail/",
        views.PerfilClienteDetailView.as_view(),
        name="perfil_cliente_detail",
    ),
    path(
        "perfil/<int:pk>/edit/",
        views.PerfilClienteUpdateView.as_view(),
        name="perfil_cliente_edit",
    ),
    path(
        "perfil/<int:pk>/delete/",
        views.PerfilClienteDeleteView.as_view(),
        name="perfil_cliente_delete",
    ),
    # SERVIÇOS AOS CLIENTES
    path(
        "servicos/",
        views.ClienteServicosListView.as_view(),
        name="cliente_servicos_list",
    ),
    path(
        "servicos/new/",
        views.ClienteServicosCreateView.as_view(),
        name="cliente_servicos_new",
    ),
    path(
        "servicos/<int:pk>/detail/",
        views.ClienteServicosDetailView.as_view(),
        name="cliente_servicos_detail",
    ),
    path(
        "servicos/<int:pk>/edit/",
        views.ClienteServicosUpdateView.as_view(),
        name="cliente_servicos_edit",
    ),
    path(
        "servicos/<int:pk>/delete/",
        views.ClienteServicosDeleteView.as_view(),
        name="cliente_servicos_delete",
    ),
    # FATURAS DOS CLIENTES
    path(
        "faturas/",
        views.ClienteFaturasListView.as_view(),
        name="cliente_faturas_list",
    ),
    path(
        "faturas/get/",
        views.GetClienteFaturas.as_view(),
        name="cliente_faturas_get",
    ),
    path(
        "faturas/new/",
        views.ClienteFaturasCreateView.as_view(),
        name="cliente_faturas_new",
    ),
    path(
        "faturas/<int:pk>/detail/",
        views.ClienteFaturasDetailView.as_view(),
        name="cliente_faturas_detail",
    ),
    path(
        "faturas/<int:pk>/edit/",
        views.ClienteFaturasUpdateView.as_view(),
        name="cliente_faturas_edit",
    ),
    path(
        "faturas/<int:pk>/delete/",
        views.ClienteFaturasDeleteView.as_view(),
        name="cliente_faturas_delete",
    ),
    # PAGAMENTOS DOS CLIENTES
    path(
        "pagamentos/",
        views.ClientePagamentosListView.as_view(),
        name="cliente_pagamentos_list",
    ),
    path(
        "pagamentos/new/",
        views.ClientePagamentosCreateView.as_view(),
        name="cliente_pagamentos_new",
    ),
    path(
        "pagamentos/<int:pk>/detail/",
        views.ClientePagamentosDetailView.as_view(),
        name="cliente_pagamentos_detail",
    ),
    path(
        "pagamentos/<int:pk>/edit/",
        views.ClientePagamentosUpdateView.as_view(),
        name="cliente_pagamentos_edit",
    ),
    path(
        "pagamentos/<int:pk>/delete/",
        views.ClientePagamentosDeleteView.as_view(),
        name="cliente_pagamentos_delete",
    ),
]
