# Generated by Django 2.1.2 on 2018-10-25 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_deposito', models.DateField(help_text='Data do depósito.', verbose_name='Data')),
                ('valor', models.FloatField(help_text='Valor do depósito (em R$).', verbose_name='Valor')),
                ('identificacao', models.CharField(blank=True, help_text='Identificação do depósito.', max_length=200, null=True, verbose_name='Identificação')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações acerca do depósito.', max_length=600, null=True, verbose_name='Observações')),
                ('data_add_reg', models.DateTimeField(auto_now_add=True, help_text='Data do cadastro do depósito.', verbose_name='Cadastrado em')),
                ('data_mod_reg', models.DateTimeField(auto_now=True, help_text='Data da modificação do depósito.', verbose_name='Modificado em')),
                ('consolidado', models.BooleanField(default=False, help_text='Define se o depósito pode ou não ser utilizado', verbose_name='Consolidado')),
                ('usuario', models.ForeignKey(blank=True, help_text='Último usuário a interagir com o depósito.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Depósito Bancário',
                'verbose_name_plural': 'Controle de Depósitos Bancários',
            },
        ),
    ]
