# Generated by Django 2.1.4 on 2019-01-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositos',
            name='identificacao',
            field=models.CharField(default='Depósito não identificado', help_text='Identificação do depósito.', max_length=200, verbose_name='Identificação'),
        ),
    ]
