# Generated by Django 2.1.4 on 2019-01-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0002_auto_20190118_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositos',
            name='identificacao',
            field=models.CharField(help_text='Identificação do depósito.', max_length=200, verbose_name='Identificação'),
        ),
    ]
