# Generated by Django 2.2.1 on 2019-05-20 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0004_auto_20190204_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositos',
            name='data_deposito',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data do depósito.', verbose_name='Data'),
        ),
    ]
