# Generated by Django 2.2.1 on 2019-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0005_auto_20190520_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositos',
            name='data_deposito',
            field=models.DateField(help_text='Data do depósito.', verbose_name='Data'),
        ),
    ]
