# Generated by Django 2.2.1 on 2019-05-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0006_auto_20190520_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositos',
            options={'ordering': ['-data_deposito', '-id', 'identificacao', 'valor'], 'verbose_name': 'Depósito Bancário', 'verbose_name_plural': 'Controle de Depósitos Bancários'},
        ),
    ]
