# Generated by Django 2.2.1 on 2019-06-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0007_auto_20190530_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositos',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor do depósito (em R$).', max_digits=20, verbose_name='Valor'),
        ),
    ]
