# Generated by Django 2.2.16 on 2020-11-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0008_auto_20190604_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositos',
            name='valor_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor utilizado do depósito (em R$).', max_digits=20, null=True, verbose_name='Valor Utilizado'),
        ),
    ]
