# Generated by Django 2.1.2 on 2018-10-25 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depositos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guiches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, help_text='Banco do cheque.', max_length=200, null=True, verbose_name='Banco')),
                ('numero', models.CharField(blank=True, help_text='Número do cheque.', max_length=200, null=True, verbose_name='Número do cheque')),
                ('data', models.DateField(blank=True, help_text='Data do cheque.', null=True, verbose_name='Data')),
                ('valor', models.FloatField(help_text='Valor do cheque.', verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(blank=True, help_text='Comprovantes de pagamentos.', max_length=200, null=True, verbose_name='Comprovantes')),
                ('valor', models.FloatField(help_text='Valor do documento.', verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do fechamento de caixa.', verbose_name='Data')),
                ('saldo_inicial', models.FloatField(help_text='Valor pre-existente no caixa.', verbose_name='Saldo Inicial')),
                ('valor_dinheiro_caixa', models.FloatField(help_text='Valor do caixa em dinheiro.', verbose_name='Dinheiro em caixa')),
                ('valor_dinheiro_cofre', models.FloatField(help_text='Valor em dinheiro enviado ao cofre.', verbose_name='Dinheiro para o cofre')),
                ('valor_depositos', models.FloatField(help_text='Valor total do caixa em depósitos (enviado ao cofre).', verbose_name='Valor em Depósitos')),
                ('valor_cheques', models.FloatField(help_text='Valor total do caixa em cheques (enviado ao cofre).', verbose_name='Valor em Cheques')),
                ('valor_comprovantes', models.FloatField(help_text='Valor total do caixa em comprovantes (enviado ao cofre).', verbose_name='Valor em Comprovantes')),
                ('valor_total', models.FloatField(help_text='Valor total do fechamento de caixa.', verbose_name='Valor Total')),
                ('fechado', models.BooleanField(default=False, help_text='Indica se o fechamento de caixa já pode ser enviado para análise do setor financeiro.', verbose_name='Entregar Fechamento')),
                ('consolidado', models.BooleanField(default=False, help_text='Indica se o valor foi consolidado pelo setor financeiro.', verbose_name='Consolidado')),
                ('qtd_devolucoes', models.PositiveIntegerField(blank=True, help_text='Quantidade de devoluções efetuadas até o fechamento do caixa.', null=True, verbose_name='Devoluções')),
                ('qtd_moeda_01cent', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,01.', null=True, verbose_name='R$ 0,01')),
                ('qtd_moeda_05cent', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,05.', null=True, verbose_name='R$ 0,05')),
                ('qtd_moeda_10cent', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,10.', null=True, verbose_name='R$ 0,10')),
                ('qtd_moeda_25cent', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,25.', null=True, verbose_name='R$ 0,25')),
                ('qtd_moeda_50cent', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,50.', null=True, verbose_name='R$ 0,50')),
                ('qtd_moeda_01real', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 1,00.', null=True, verbose_name='R$ 1,00')),
                ('qtd_moeda_02reais', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 2,00.', null=True, verbose_name='R$ 2,00')),
                ('qtd_moeda_05reais', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 5,00.', null=True, verbose_name='R$ 5,00')),
                ('qtd_moeda_10reais', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 10,00.', null=True, verbose_name='R$ 10,00')),
                ('qtd_moeda_20reais', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 20,00.', null=True, verbose_name='R$ 20,00')),
                ('qtd_moeda_50reais', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 50,00.', null=True, verbose_name='R$ 50,00')),
                ('qtd_moeda_100reais', models.PositiveIntegerField(blank=True, help_text='Quantidade de moedas de R$ 100,00.', null=True, verbose_name='R$ 100,00')),
            ],
            options={
                'verbose_name': 'Fechamento de Caixa',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoDeposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Valor do depósito usado no fechamento de caixa.', verbose_name='Valor')),
                ('deposito', models.ForeignKey(help_text='Depósito bancário relacionado.', on_delete=django.db.models.deletion.PROTECT, to='depositos.Depositos', verbose_name='Depósito')),
                ('fechamento_caixa', models.ForeignKey(help_text='Fechamento de caixa relacionado.', on_delete=django.db.models.deletion.PROTECT, to='caixa.FechamentoCaixa', verbose_name='Fechamento de caixa')),
            ],
            options={
                'verbose_name': 'Lançamento de Depósito',
                'verbose_name_plural': 'Lançamento de Depósitos',
            },
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='depositos',
            field=models.ManyToManyField(through='caixa.LancamentoDeposito', to='depositos.Depositos'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='guiche',
            field=models.ForeignKey(help_text='Guichê do fechamento de caixa.', on_delete=django.db.models.deletion.PROTECT, to='guiches.Guiche', verbose_name='Guichê'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável pelo fechamento de caixa.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='fechamento_caixa',
            field=models.ForeignKey(blank=True, help_text='Fechamento de caixa no qual o comprovante foi utilizado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='caixa.FechamentoCaixa', verbose_name='Fechamento de caixa'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='fechamento_caixa',
            field=models.ForeignKey(blank=True, help_text='Fechamento de caixa no qual o cheque foi utilizado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='caixa.FechamentoCaixa', verbose_name='Fechamento de caixa'),
        ),
        migrations.AlterUniqueTogether(
            name='fechamentocaixa',
            unique_together={('usuario', 'data')},
        ),
    ]
