# Generated by Django 2.1.2 on 2018-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='valor_quebra',
            field=models.FloatField(help_text='Valor da diferença entre o fechamento de caixa e o caixa do register.', null=True, verbose_name='Valor Quebra de Caixa'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='valor_total_entrada',
            field=models.FloatField(help_text='Valor total dos valores que entraram no caixa.', null=True, verbose_name='Valor Total de Entrada'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='saldo_inicial',
            field=models.FloatField(help_text='Valor pre-existente no caixa.', null=True, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_cheques',
            field=models.FloatField(help_text='Valor total do caixa em cheques (enviado ao cofre).', null=True, verbose_name='Valor em Cheques'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_comprovantes',
            field=models.FloatField(help_text='Valor total do caixa em comprovantes (enviado ao cofre).', null=True, verbose_name='Valor em Comprovantes'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_depositos',
            field=models.FloatField(help_text='Valor total do caixa em depósitos (enviado ao cofre).', null=True, verbose_name='Valor em Depósitos'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_dinheiro_caixa',
            field=models.FloatField(help_text='Valor do caixa em dinheiro.', null=True, verbose_name='Dinheiro em caixa'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_dinheiro_cofre',
            field=models.FloatField(help_text='Valor em dinheiro enviado ao cofre.', null=True, verbose_name='Dinheiro para o cofre'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_total',
            field=models.FloatField(help_text='Valor total do fechamento de caixa.', null=True, verbose_name='Valor Total Geral'),
        ),
    ]
