# Generated by Django 2.1.2 on 2018-11-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0001_initial'),
        ('caixa', '0003_cheque_emitente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lancamentodeposito',
            unique_together={('fechamento_caixa', 'deposito')},
        ),
    ]
