# Generated by Django 2.1.2 on 2018-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_auto_20181116_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações acerca do fechamento de caixa.', null=True, verbose_name='Observações'),
        ),
    ]
