# Generated by Django 2.1.2 on 2018-12-03 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caixa', '0005_fechamentocaixa_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='data_add_reg',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data do cadastro do fechamento de caixa.', verbose_name='Cadastrado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='data_mod_reg',
            field=models.DateTimeField(auto_now=True, help_text='Data da modificação do fechamento de caixa.', verbose_name='Modificado em'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='usuario_mod',
            field=models.ForeignKey(blank=True, help_text='Último usuário a interagir com o depósito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_mod', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
