# Generated by Django 2.1.2 on 2018-12-03 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_auto_20181203_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='usuario_mod',
            field=models.ForeignKey(blank=True, editable=False, help_text='Último usuário a interagir com o depósito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_mod', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
