# Generated by Django 2.1.2 on 2018-12-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0007_auto_20181203_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='data_add_reg',
        ),
    ]
