# Generated by Django 2.1.2 on 2018-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0008_remove_fechamentocaixa_data_add_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='historico',
            field=models.TextField(editable=False, help_text='Histórico de ações no registro do fechamento de caixa.', null=True, verbose_name='Histórico'),
        ),
    ]
