# Generated by Django 2.1.2 on 2018-12-05 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0009_fechamentocaixa_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='data_mod_reg',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Data da modificação do fechamento de caixa.', verbose_name='Modificado em'),
        ),
    ]
