# Generated by Django 2.1.2 on 2018-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0010_auto_20181205_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='data_mod_reg',
            field=models.DateTimeField(blank=True, editable=False, help_text='Data da modificação do fechamento de caixa.', verbose_name='Modificado em'),
        ),
    ]
