# Generated by Django 2.1.5 on 2019-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0011_auto_20181205_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='valor_desp_futuras',
            field=models.FloatField(help_text='Valor total dos valores a serem utilizados para despesas posteriores.', null=True, verbose_name='Valor de Despesas Futuras'),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='valor_pos_pagamento',
            field=models.FloatField(help_text='Valor total dos pagamentos posteriores.', null=True, verbose_name='Valor em Pagamentos Posteriores'),
        ),
    ]
