# Generated by Django 2.1.5 on 2019-01-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0012_auto_20190128_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechamentocaixa',
            old_name='valor_pos_pagamento',
            new_name='valor_total_servicos_clientes',
        ),
    ]
