# Generated by Django 2.1.7 on 2019-02-21 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caixa', '0013_auto_20190128_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descritivo da configuração', max_length=120, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a configuração está ou não ativa.', verbose_name='Ativo?')),
                ('qtd_moeda_01cent', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,01.', null=True, verbose_name='R$ 0,01')),
                ('qtd_moeda_05cent', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,05.', null=True, verbose_name='R$ 0,05')),
                ('qtd_moeda_10cent', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,10.', null=True, verbose_name='R$ 0,10')),
                ('qtd_moeda_25cent', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,25.', null=True, verbose_name='R$ 0,25')),
                ('qtd_moeda_50cent', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 0,50.', null=True, verbose_name='R$ 0,50')),
                ('qtd_moeda_01real', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 1,00.', null=True, verbose_name='R$ 1,00')),
                ('qtd_moeda_02reais', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 2,00.', null=True, verbose_name='R$ 2,00')),
                ('qtd_moeda_05reais', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 5,00.', null=True, verbose_name='R$ 5,00')),
                ('qtd_moeda_10reais', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 10,00.', null=True, verbose_name='R$ 10,00')),
                ('qtd_moeda_20reais', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 20,00.', null=True, verbose_name='R$ 20,00')),
                ('qtd_moeda_50reais', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 50,00.', null=True, verbose_name='R$ 50,00')),
                ('qtd_moeda_100reais', models.PositiveSmallIntegerField(blank=True, help_text='Quantidade de moedas de R$ 100,00.', null=True, verbose_name='R$ 100,00')),
                ('usuarios', models.ManyToManyField(help_text='Usuários aos quais se aplica a configuração de caixa.', null=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Configuração de Caixa',
                'verbose_name_plural': 'Configurações de Caixas',
            },
        ),
    ]
