# Generated by Django 2.1.7 on 2019-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0015_auto_20190221_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocaixa',
            name='precedencia',
            field=models.PositiveSmallIntegerField(default=0, help_text='O valor da precedência é usado para tomada de decisões acerca da            configuração a ser usada. (Ordem crescente)', unique=True, verbose_name='Precedência'),
            preserve_default=False,
        ),
    ]
