# Generated by Django 2.2.1 on 2019-06-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0016_configuracaocaixa_precedencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor do cheque.', max_digits=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor do documento.', max_digits=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, help_text='Valor pre-existente no caixa.', max_digits=20, null=True, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_cheques',
            field=models.DecimalField(decimal_places=2, help_text='Valor total do caixa em cheques (enviado ao cofre).', max_digits=20, null=True, verbose_name='Valor em Cheques'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_comprovantes',
            field=models.DecimalField(decimal_places=2, help_text='Valor total do caixa em comprovantes (enviado ao cofre).', max_digits=20, null=True, verbose_name='Valor em Comprovantes'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_depositos',
            field=models.DecimalField(decimal_places=2, help_text='Valor total do caixa em depósitos (enviado ao cofre).', max_digits=20, null=True, verbose_name='Valor em Depósitos'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_desp_futuras',
            field=models.DecimalField(decimal_places=2, help_text='Valor total dos valores a serem utilizados para despesas posteriores.', max_digits=20, null=True, verbose_name='Valor de Despesas Futuras'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_dinheiro_caixa',
            field=models.DecimalField(decimal_places=2, help_text='Valor do caixa em dinheiro.', max_digits=20, null=True, verbose_name='Dinheiro em caixa'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_dinheiro_cofre',
            field=models.DecimalField(decimal_places=2, help_text='Valor em dinheiro enviado ao cofre.', max_digits=20, null=True, verbose_name='Dinheiro para o cofre'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_quebra',
            field=models.DecimalField(decimal_places=2, help_text='Valor da diferença entre o fechamento de caixa e o caixa do register.', max_digits=20, null=True, verbose_name='Valor Quebra de Caixa'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, help_text='Valor total do fechamento de caixa.', max_digits=20, null=True, verbose_name='Valor Total Geral'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_total_entrada',
            field=models.DecimalField(decimal_places=2, help_text='Valor total dos valores que entraram no caixa.', max_digits=20, null=True, verbose_name='Valor Total de Entrada'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_total_servicos_clientes',
            field=models.DecimalField(decimal_places=2, help_text='Valor total dos pagamentos posteriores.', max_digits=20, null=True, verbose_name='Valor em Pagamentos Posteriores'),
        ),
        migrations.AlterField(
            model_name='lancamentodeposito',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor do depósito usado no fechamento de caixa.', max_digits=20, verbose_name='Valor'),
        ),
    ]
