# Generated by Django 2.2.2 on 2019-10-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0017_auto_20190604_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='valor_cartoes',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Valor total do caixa pago em cartões (compõe o valor em comprovantes).', max_digits=20, null=True, verbose_name='Valor em Cartões'),
        ),
    ]
