# Generated by Django 2.2.17 on 2020-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0018_fechamentocaixa_valor_cartoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='observacoes',
            field=models.TextField(blank=True, default='', help_text='Observações acerca do fechamento de caixa.', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_devolucoes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de devoluções efetuadas até o fechamento do caixa.', null=True, verbose_name='Devoluções'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_01cent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 0,01.', null=True, verbose_name='R$ 0,01'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_01real',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 1,00.', null=True, verbose_name='R$ 1,00'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_02reais',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 2,00.', null=True, verbose_name='R$ 2,00'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_05cent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 0,05.', null=True, verbose_name='R$ 0,05'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_05reais',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 5,00.', null=True, verbose_name='R$ 5,00'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_100reais',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 100,00.', null=True, verbose_name='R$ 100,00'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_10cent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 0,10.', null=True, verbose_name='R$ 0,10'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_10reais',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 10,00.', null=True, verbose_name='R$ 10,00'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_20reais',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 20,00.', null=True, verbose_name='R$ 20,00'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_25cent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 0,25.', null=True, verbose_name='R$ 0,25'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_50cent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 0,50.', null=True, verbose_name='R$ 0,50'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='qtd_moeda_50reais',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de moedas de R$ 50,00.', null=True, verbose_name='R$ 50,00'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor pre-existente no caixa.', max_digits=20, null=True, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_cartoes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total do caixa pago em cartões (compõe o valor em comprovantes).', max_digits=20, null=True, verbose_name='Valor em Cartões'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_cheques',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total do caixa em cheques (enviado ao cofre).', max_digits=20, null=True, verbose_name='Valor em Cheques'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_comprovantes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total do caixa em comprovantes (enviado ao cofre).', max_digits=20, null=True, verbose_name='Valor em Comprovantes'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_depositos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total do caixa em depósitos (enviado ao cofre).', max_digits=20, null=True, verbose_name='Valor em Depósitos'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_desp_futuras',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total dos valores a serem utilizados para despesas posteriores.', max_digits=20, null=True, verbose_name='Valor de Despesas Futuras'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_dinheiro_caixa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor do caixa em dinheiro.', max_digits=20, null=True, verbose_name='Dinheiro em caixa'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_dinheiro_cofre',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor em dinheiro enviado ao cofre.', max_digits=20, null=True, verbose_name='Dinheiro para o cofre'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_quebra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor da diferença entre o fechamento de caixa e o caixa do register.', max_digits=20, null=True, verbose_name='Valor Quebra de Caixa'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total do fechamento de caixa.', max_digits=20, null=True, verbose_name='Valor Total Geral'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_total_entrada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total dos valores que entraram no caixa.', max_digits=20, null=True, verbose_name='Valor Total de Entrada'),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_total_servicos_clientes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total dos pagamentos posteriores.', max_digits=20, null=True, verbose_name='Valor em Pagamentos Posteriores'),
        ),
    ]
