# Generated by Django 2.2.17 on 2020-11-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0019_auto_20201113_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='fechamento_caixa',
            field=models.ForeignKey(help_text='Fechamento de caixa no qual o comprovante foi utilizado.', on_delete=django.db.models.deletion.CASCADE, to='caixa.FechamentoCaixa', verbose_name='Fechamento de caixa'),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='identificacao',
            field=models.CharField(help_text='Comprovantes de pagamentos.', max_length=200, verbose_name='Comprovantes'),
        ),
    ]
