# Generated by Django 2.1.4 on 2019-01-22 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Identificação do Cliente', max_length=200, verbose_name='Nome')),
                ('tipo_documento', models.CharField(choices=[('PF', 'PF'), ('PJ', 'PJ'), ('EX', 'Estrangeiro')], help_text='Tipo de documento utilizado.', max_length=2, verbose_name='Tipo de documento')),
                ('cpf', models.CharField(blank=True, help_text='Cadastro de Pessoa Física. (Somente dígitos)', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, help_text='Cadastro Nacional de Pessoa Jurídica. (Somente dígitos)', max_length=16, null=True, unique=True, verbose_name='CNPJ')),
                ('estrangeiro', models.CharField(blank=True, help_text='Documento estrangeiro de identificação.', max_length=20, null=True, unique=True, verbose_name='Documento Estrangeiro')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato.', max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, help_text='Endereço completo do cliente.', max_length=400, null=True, verbose_name='Endereço')),
                ('endereco_complemento', models.CharField(blank=True, help_text='Complemento o endereço.', max_length=200, null=True, verbose_name='Complemento')),
                ('periodo_pag', models.CharField(choices=[('SE', 'Semanal'), ('QE', 'Quinzenal'), ('ME', 'Mensal'), ('BM', 'Bimestral'), ('TM', 'Trimestral'), ('SM', 'Semestral'), ('AN', 'Anual')], help_text='Perído de tempo para fechamento de fatura.', max_length=2, verbose_name='Período de pagamento.')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o cliente pode ser utilizado.', verbose_name='Está ativo?')),
            ],
            options={
                'ordering': ['ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Identificação do perfil de cliente.', max_length=70, verbose_name='Perfil')),
                ('descricao', models.CharField(blank=True, help_text='Descrição do perfil de cliente.', max_length=200, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o perfil de cliente pode ser utilizado.', verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfis de Clientes',
                'ordering': ['ativo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.ForeignKey(blank=True, help_text='Identificação do perfil de cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.PerfilCliente', verbose_name='Perfil'),
        ),
    ]
