# Generated by Django 2.1.4 on 2019-01-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='periodo_pag',
            field=models.CharField(blank=True, choices=[('SE', 'Semanal'), ('QE', 'Quinzenal'), ('ME', 'Mensal'), ('BM', 'Bimestral'), ('TM', 'Trimestral'), ('SM', 'Semestral'), ('AN', 'Anual')], help_text='Perído de tempo para fechamento de fatura.', max_length=2, null=True, verbose_name='Período de pagamento.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('PF', 'PF'), ('PJ', 'PJ'), ('EX', 'Estrangeiro')], help_text='Tipo de documento utilizado.', max_length=2, null=True, verbose_name='Tipo de documento'),
        ),
    ]
