# Generated by Django 2.1.5 on 2019-01-23 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20190123_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteservicos',
            name='protocolo',
            field=models.PositiveIntegerField(blank=True, help_text='Protocolo do serviço prestado no register.', null=True, validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='Protocolo'),
        ),
    ]
