# Generated by Django 2.1.5 on 2019-01-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_clienteservicos_contabilizar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteservicos',
            options={'ordering': ['contabilizar', 'liquidado', '-data', 'cliente', 'tipo_protocolo', 'protocolo', 'valor'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços prestados ao clientes'},
        ),
    ]
