# Generated by Django 2.1.5 on 2019-01-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20190123_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteservicos',
            options={'ordering': ['contabilizar', 'liquidado', '-data', 'cliente', 'tipo_protocolo', 'protocolo', 'valor'], 'verbose_name': 'Serviço ao cliente', 'verbose_name_plural': 'Serviços prestados ao Clientes'},
        ),
    ]
