# Generated by Django 2.1.5 on 2019-01-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20190123_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, default=None, help_text='Cadastro Nacional de Pessoa Jurídica. (Somente dígitos)', max_length=16, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default=None, help_text='Cadastro de Pessoa Física. (Somente dígitos)', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estrangeiro',
            field=models.CharField(blank=True, default=None, help_text='Documento estrangeiro de identificação.', max_length=20, null=True, unique=True, verbose_name='Documento Estrangeiro'),
        ),
    ]
