# Generated by Django 2.1.5 on 2019-01-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20190123_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteservicos',
            old_name='caixa',
            new_name='fechamento_caixa',
        ),
    ]
