# Generated by Django 2.1.5 on 2019-01-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20190128_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteservicos',
            old_name='fechamento_caixa',
            new_name='caixa',
        ),
    ]
