# Generated by Django 2.1.5 on 2019-01-30 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_auto_20190128_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteservicos',
            name='valor',
            field=models.FloatField(help_text='Valor do serviço prestado.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor'),
        ),
    ]
