# Generated by Django 2.1.5 on 2019-01-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_auto_20190130_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteservicos',
            options={'ordering': ['contabilizar', 'liquidado', 'caixa', '-data', 'cliente', 'tipo_protocolo', 'protocolo', 'valor'], 'verbose_name': 'Serviço ao cliente', 'verbose_name_plural': 'Serviços prestados ao Clientes'},
        ),
    ]
