# Generated by Django 2.1.5 on 2019-01-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20190130_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteservicos',
            options={'ordering': ['contabilizar', '-data', 'liquidado', '-caixa', 'cliente', 'tipo_protocolo', 'protocolo', 'valor'], 'verbose_name': 'Serviço ao cliente', 'verbose_name_plural': 'Serviços prestados ao Clientes'},
        ),
    ]
