# Generated by Django 2.1.5 on 2019-02-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_auto_20190130_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-ativo', 'nome']},
        ),
    ]
