# Generated by Django 2.1.5 on 2019-02-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_auto_20190206_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilcliente',
            options={'ordering': ['ativo', 'nome'], 'verbose_name': 'Perfil de Cliente', 'verbose_name_plural': 'Perfís de Clientes'},
        ),
    ]
