# Generated by Django 2.1.5 on 2019-02-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_auto_20190211_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilcliente',
            options={'ordering': ['-ativo', 'nome'], 'verbose_name': 'Perfil de Cliente', 'verbose_name_plural': 'Perfís de Clientes'},
        ),
    ]
