# Generated by Django 2.1.5 on 2019-02-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_auto_20190211_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='perfil',
            field=models.ForeignKey(blank=True, help_text='Identificação do perfil de cliente.', limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.PerfilCliente', verbose_name='Perfil'),
        ),
    ]
