# Generated by Django 2.1.7 on 2019-02-28 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0004_auto_20190204_1540'),
        ('clientes', '0021_auto_20190211_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fatura', models.DateField(auto_now_add=True, help_text='Data em que a fatura foi gerada.', verbose_name='Data da fatura')),
                ('valor_servicos', models.FloatField(help_text='Valor total dos serviços relacionados à fatura.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor dos serviços')),
                ('descontos_valor', models.FloatField(blank=True, help_text='Valor total dos descontos incidentes sobre a fatura, quando houver.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor dos descontos')),
                ('valor_fatura', models.FloatField(help_text='Valor total da fatura, observando-se os serviços e descosntos.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor da fatura')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais acerca da fatura.', null=True, verbose_name='Observações')),
                ('liquidado', models.BooleanField(default=False, help_text='Indica se a fatura já foi ou não paga.', verbose_name='Liquidado?')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data do pagamento da fatura.', null=True, verbose_name='Data do pagamento')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('DP', 'Depósito'), ('DI', 'Dinheiro'), ('CQ', 'Cheque')], default=None, max_length=2, null=True, verbose_name='Forma de pagamento')),
                ('cliente', models.ForeignKey(help_text='Cliente da fatura.', on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Cliente')),
                ('deposito', models.ForeignKey(blank=True, help_text='Identificação do depósito utilizado no pagamento.', null=True, on_delete=django.db.models.deletion.PROTECT, to='depositos.Depositos', verbose_name='Depósito')),
            ],
            options={
                'verbose_name': 'Fatura de Serviços ao Cliente',
                'verbose_name_plural': 'Faturas de Serviços aos Clientes',
                'ordering': ['liquidado', '-data_fatura', 'cliente', '-data_pagamento'],
            },
        ),
    ]
