# Generated by Django 2.1.7 on 2019-02-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_clientefaturas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientefaturas',
            old_name='descontos_valor',
            new_name='valor_descontos',
        ),
    ]
