# Generated by Django 2.1.7 on 2019-03-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_auto_20190228_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteservicos',
            name='fatura',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Indica a fatura à qual o serviço está relacionado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.ClienteFaturas', verbose_name='Fatura'),
        ),
    ]
