# Generated by Django 2.1.7 on 2019-03-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_clienteservicos_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteservicos',
            name='caixa',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Indica em que fechamento de caixa foi realizado o serviço.', null=True, on_delete=django.db.models.deletion.PROTECT, to='caixa.FechamentoCaixa', verbose_name='Fechamento de Caixa'),
        ),
        migrations.AlterField(
            model_name='clienteservicos',
            name='fatura',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='Indica a fatura à qual o serviço está relacionado.', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.ClienteFaturas', verbose_name='Fatura'),
        ),
    ]
