# Generated by Django 2.2 on 2019-04-05 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_auto_20190403_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefaturas',
            name='valor_fatura',
            field=models.FloatField(default=0, help_text='Valor total da fatura, observando-se os serviços e descosntos.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor da fatura'),
        ),
        migrations.AlterField(
            model_name='clientefaturas',
            name='valor_servicos',
            field=models.FloatField(default=0, help_text='Valor total dos serviços relacionados à fatura.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor dos serviços'),
        ),
    ]
