# Generated by Django 2.2 on 2019-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_auto_20190405_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteservicos',
            name='observacoes',
            field=models.TextField(blank=True, default='', help_text='Notas adicionais acerca do serviço.', null=True, verbose_name='Observações'),
        ),
    ]
