# Generated by Django 2.2 on 2019-04-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0031_auto_20190423_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='outorgante',
            field=models.ForeignKey(blank=True, help_text='Pessoa/Entidade que é representada por este cliente (quando aplicável).', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Outorgante'),
        ),
    ]
