# Generated by Django 2.2 on 2019-04-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0032_auto_20190423_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço eletrônico do cliente.', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('PF', 'CPF'), ('PJ', 'CNPJ'), ('EX', 'Estrangeiro')], help_text='Tipo de documento utilizado.', max_length=2, null=True, verbose_name='Tipo de documento'),
        ),
    ]
