# Generated by Django 2.2 on 2019-04-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0033_auto_20190425_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço eletrônico do cliente.', max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
