# Generated by Django 2.2 on 2019-04-29 19:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0004_auto_20190204_1540'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0034_auto_20190425_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(blank=True, default=datetime.date(2019, 4, 29), help_text='Data do pagamento.', null=True, verbose_name='Data do pagamento')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('DP', 'Depósito'), ('DI', 'Dinheiro'), ('CQ', 'Cheque')], default='DI', max_length=2, null=True, verbose_name='Forma de pagamento')),
                ('valor', models.FloatField(help_text='Valor do pagamento.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('notas_adicionais', models.TextField(blank=True, help_text='Informações adicionais acerca do pagamento.', null=True, verbose_name='Notas Adicionais')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Data da adição do registro.')),
                ('data_mod', models.DateField(auto_now=True, verbose_name='Data da modificação do registro.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Cliente')),
                ('deposito', models.ForeignKey(blank=True, help_text='Identificação do depósito utilizado no pagamento.', null=True, on_delete=django.db.models.deletion.PROTECT, to='depositos.Depositos', verbose_name='Depósito')),
                ('usuario', models.ForeignKey(blank=True, help_text='Último usuário a interagir com o pagamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pagamento do Cliente',
                'verbose_name_plural': 'Pagamentos dos Clientes',
                'ordering': ['-data_pagamento', 'cliente', '-data_add'],
            },
        ),
    ]
