# Generated by Django 2.2 on 2019-05-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0037_auto_20190430_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientefaturas',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='clientefaturas',
            name='forma_pagamento',
        ),
    ]
