# Generated by Django 2.2.1 on 2019-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0039_auto_20190503_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='verifica_saldo',
            field=models.BooleanField(default=False, help_text='Somente serão lançados serviços ao cliente caso este possua saldo suficiente.', verbose_name='Verificação de Saldo'),
        ),
    ]
