# Generated by Django 2.2.1 on 2019-05-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0041_auto_20190520_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteservicos',
            name='data',
            field=models.DateField(help_text='Data em que foi prestado o serviço.', verbose_name='Data'),
        ),
    ]
