# Generated by Django 2.2.1 on 2019-05-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0042_auto_20190520_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, default=None, help_text='Cadastro Nacional de Pessoa Jurídica. (Somente dígitos)', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
