# Generated by Django 2.2.1 on 2019-05-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_auto_20190528_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientefaturas',
            options={'ordering': ['-data_fatura', '-id', 'liquidado', 'cliente', '-data_pagamento'], 'verbose_name': 'Fatura de Serviços ao Cliente', 'verbose_name_plural': 'Faturas de Serviços aos Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientepagamentos',
            options={'ordering': ['-data_pagamento', '-id', '-data_add'], 'verbose_name': 'Pagamento do Cliente', 'verbose_name_plural': 'Pagamentos dos Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clienteservicos',
            options={'ordering': ['-data', '-id', 'contabilizar', 'liquidado', '-caixa', 'cliente', 'tipo_protocolo', 'protocolo', 'valor'], 'verbose_name': 'Serviço ao cliente', 'verbose_name_plural': 'Serviços prestados ao Clientes'},
        ),
    ]
