# Generated by Django 2.2.1 on 2019-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0044_auto_20190530_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Saldo disponível na conta do cliente.', max_digits=20, null=True, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo_faturado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Saldo entre receitas e despesas das faturas.', max_digits=20, null=True, verbose_name='Saldo Faturado'),
        ),
    ]
