# Generated by Django 2.2.17 on 2020-11-23 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0045_auto_20190604_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefaturas',
            name='valor_fatura',
            field=models.FloatField(blank=True, default=0, help_text='Valor total da fatura, observando-se os serviços e descontos.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor da fatura'),
        ),
    ]
