# Generated by Django 2.1.2 on 2018-10-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do guichê.', max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, help_text='Descrição do guichê.', max_length=400, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o guichê está ativo ou não.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Guichê',
                'verbose_name_plural': 'Guichês',
                'ordering': ['nome'],
            },
        ),
    ]
