# Generated by Django 2.1.2 on 2018-11-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiche',
            name='id_register',
            field=models.PositiveIntegerField(blank=True, help_text='ID do guichê no Register.', null=True, verbose_name='ID Register'),
        ),
    ]
