# Generated by Django 2.1.2 on 2018-12-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiches', '0002_guiche_id_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiche',
            name='id_register',
            field=models.PositiveIntegerField(blank=True, help_text='ID do guichê no Register.', null=True, unique=True, verbose_name='ID Register'),
        ),
    ]
