# Generated by Django 2.1.4 on 2019-01-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_receita', models.PositiveIntegerField(help_text='Código da despesa conforme tabela da Receita Federal.', unique=True, verbose_name='Código')),
                ('identificacao', models.CharField(help_text='Discriminação do tipo de despesa.', max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o tipo de despesa está ativo e pode ser utilizado.', verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Categoria da Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'ordering': ['ativo', 'codigo_receita'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(help_text='Data da despesa.', verbose_name='Data')),
                ('identificacao', models.CharField(help_text='Discriminação da despesa.', max_length=200, verbose_name='Despesa')),
                ('valor', models.FloatField(help_text='Valor do documento.', verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, help_text='Observações acerca da despesa.', null=True, verbose_name='Observações')),
                ('categoria_despesa', models.ForeignKey(help_text='Categoria da despesa conforme tabela da Receita Federal.', on_delete=django.db.models.deletion.PROTECT, to='despesas.CategoriaDespesa', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_despesa', 'categoria_despesa', 'identificacao'],
            },
        ),
    ]
