# Generated by Django 2.1.5 on 2019-01-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadespesa',
            options={'ordering': ['ativo', 'codigo_rf'], 'verbose_name': 'Categoria da Despesa', 'verbose_name_plural': 'Categorias de Despesas'},
        ),
        migrations.RenameField(
            model_name='categoriadespesa',
            old_name='codigo_receita',
            new_name='codigo_rf',
        ),
    ]
