# Generated by Django 2.2.2 on 2019-06-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_auto_20190611_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='identificacao',
            field=models.CharField(help_text='Discriminação da despesa.', max_length=200, verbose_name='Descrição'),
        ),
    ]
