# Generated by Django 2.2.2 on 2019-07-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0006_auto_20190628_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricosDespesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Descrição da despesa.', max_length=250, verbose_name='Histórico')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
            },
        ),
    ]
