# Generated by Django 2.2.2 on 2019-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0007_historicosdespesas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicosdespesas',
            options={'ordering': ['identificacao'], 'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
    ]
