# Generated by Django 2.2.2 on 2019-07-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0008_auto_20190701_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='identificacao',
            field=models.ForeignKey(help_text='Descrição da despesa.', on_delete=django.db.models.deletion.PROTECT, to='despesas.HistoricosDespesas', verbose_name='Histórico'),
        ),
    ]
