# Generated by Django 2.2.2 on 2019-07-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0009_auto_20190701_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicosdespesas',
            options={'ordering': ['identificacao'], 'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos de Despesas'},
        ),
    ]
