# Generated by Django 2.2.2 on 2019-09-20 19:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_cartoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosCartoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Data em que foi adicionado o registro.', verbose_name='Data do registro')),
                ('operacao', models.CharField(choices=[('DB', 'Débito'), ('CR', 'Crédito')], help_text='Tipo de lançamento registrado.', max_length=2, verbose_name='Operação')),
                ('valor_servico', models.DecimalField(decimal_places=2, help_text='Valor do serviço registrado.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do serviço')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, help_text='Valor da cobrança (somados os juros ao valor do serviço).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor cobrado')),
                ('taxa_juros', models.DecimalField(decimal_places=2, help_text='Taxa de juros aplicada à transação.', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de juros')),
                ('parcelas', models.PositiveSmallIntegerField(blank=True, default=None, help_text='Quantidade de parcelas (quando aplicável).', null=True, verbose_name='Parcelas')),
                ('protocolo', models.CharField(blank=True, default=None, help_text='Protocolos relacionados ao registro.', max_length=30, null=True, verbose_name='Protocolo')),
                ('bandeira', models.ForeignKey(help_text='Bandeira do cartão.', on_delete=django.db.models.deletion.PROTECT, to='api_cartoes.Bandeiras', verbose_name='Bandeira')),
                ('usuario', models.ForeignKey(help_text='Usuário que incluiu o registro.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
